### ISSUE TITLE
Issue: Reliability of JSON Conversion for Synthea C-CDA Records

### ISSUE THREAD

**Issue by avinashkurup** [rtyler/xmltojson#3]
Hi,

I am using the xmltojson library to convert [Synthea C-CDA XML records](https://synthetichealth.github.io/synthea-sample-data/downloads/latest/synthea_sample_data_ccda_latest.zip) into JSON format. My goal is to work directly with JSON data, as I am using SQLite, which natively supports JSON functions. This avoids the complexity of setting up XML support in SQLite, which would require custom extensions that are challenging to implement, especially for advanced data extractions.

Could you confirm if the JSON produced by this library reliably retains the structure and details of the original XML, particularly for complex C-CDA documents? Any known limitations or edge cases with this type of data would be helpful to know.

The C-CDA documents contain healthcare information that requires a consistent and accurate format in JSON to allow advanced querying within SQLite. Any guidance on using this library for such structured data would be much appreciated!

Thank you!

**Comment by rtyler** [comment]
As an open source project with no warranties as stated in the license. However I am able to offer support contracts for commercial entities, please contact me at : rtyler@buoyantdata.com

**Comment by avinashkurup** [comment]
Thank you @rtyler for the prompt response! I understand the limitations as an open-source project and appreciate the clarification. At this time, I’ll continue exploring the JSON output from the library for my needs. However, I do have a concern regarding data fidelity:

Is there a possibility for the conversion process to introduce issues due to XML to JSON transformation being inherently lossy, especially with complex or nested XML structures like C-CDA. The structure includes attributes, namespaces, and mixed content, would these always translate perfectly into JSON? Could this lead to nuances being lost, potentially impacting the fidelity of the data.

Should there be a requirement for extended support or a commercial arrangement to address such concerns, I’ll reach out directly to discuss options.

Thanks again for your work on this project!
